#!/bin/sh
':' //; exec "$(command -v nodejs || command -v node)" "$0" "$@"

function argparse(args) {
    var res = {}
    for (var i = 0 ; i < args.length ; i ++ ) {
        if (args[i][0] == '-') {
            res[args[i]] = [];
            var j = i + 1;
            while (j < args.length && args[j][0] != '-') {
                res[args[i]].push(args[j])
                j += 1;
            }
            res[args[i]] = res[args[i]].join(' ') == '' ? true : res[args[i]].join(' ');
            i = j - 1;
        }
    }

    return res;
}

var workerPath = process.argv[2] + '/main.js';
var port = parseInt(process.argv[3]);

//worker arguments
var workerArgs = process.argv.slice(4);

//export worker
var worker = require(__dirname + '/worker/' + workerPath)

//intialize arguments
worker.init(argparse(workerArgs));

//create server
var app = require('http').createServer(worker.server)
app.listen(port);

if (worker.io) {
	var io = require('socket.io')(app);
	io.on('connection', worker.io);
}

console.log(process.argv[2] + ' worker started on port ' + port);
