#!/usr/bin/env python

import sys

attributes = set()

inFile = open(sys.argv[1],'r')

for line in inFile:
	if line[0] == '>':
		attributes.add(line[1:].strip())

attributes.remove('na')
attributes = list(attributes)

print '\n'.join(attributes)
