#!/usr/bin/env python 

import sys

inFile = open(sys.argv[1],'r')

tracks = set()

for line in inFile:
	meta = line.strip().split('\t')
	if len(meta) > 1:
		tracks.add(meta[-1])

tracks = list(tracks)
print '\n'.join(tracks)
